services:
  - type: web
    name: hubspot-mock-api
    runtime: node
    buildCommand: cd hubspot-mock-api && npm install
    startCommand: cd hubspot-mock-api && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
